# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a97a06e8bfd6e758dacfcb6d260e0ae2a0ce94b9a1582303c35d3800cdfdd0d6eb7e9ddee4944b59468c61ad687815c770754a3c52880217a5f1a0978a746c19

test:
  secret_key_base: acd1fb4535e2c1ad8007ca3437ba6bb1414d6d02deb91146513041ca6f59febe6df0a585491c6c8bff08b4f438a6bac300a4e156da29e56617a789c57ff2e728

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
